name: Bug Report
description: Create a bug report to help us find and fix bugs!
title: "[Bug] "
type: "Bug"
labels: [bug]
projects: "SpaceTheme/3"
assignees: SpaceEnergy
body:
  - type: checkboxes
    attributes:
      label: Step 1. Pre-report Checklist
      description: Please check the following before reporting a bug. This helps us to quickly identify and resolve issues.
      options:
      - label: I checked if there is already an open issue that described my problem.
        required: true
      - label: I checked if there is already an open issue at [Vencord](https://github.com/Vendicated/Vencord/issues) that describes my problem.
        required: true
      - label: I ticked the checkboxes without reading them.
        required: false
      - label: I restarted Discord for the newest version.
        required: false
  - type: textarea
    attributes:
      label: Step 2. Theme configuration
      description: Please provide your current theme configuration.
      value: |
        <details><summary>Configuration</summary>

          ```
          Just replace the text here in the ``` with the theme file content.
          ```
        </details>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Step 3. Describe the issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: Step 4. How to reproduce
      placeholder: |
        1. Go to a forum
        2. Click on a post
        3. Scroll scroll a bit up
        4. See bug...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.